<x-admin-layout>
    <x-slot name="header">AI Analysis Report #{{ $diagnosis->id ?? $id }}</x-slot>
    <x-slot name="description">VehiCare Intelligent Diagnostic Assessment & Recommended Repair Steps</x-slot>

    @php
        $minCost = (float)($diagnosis->estimated_cost_min ?? 0);
        $maxCost = (float)($diagnosis->estimated_cost_max ?? 0);
        $hasCost = $minCost > 0 || $maxCost > 0;
        $currencyCode = $diagnosis->currency ?? 'PHP';

        $severity = strtoupper($diagnosis->severity ?? 'LOW');
        $urgency = $diagnosis->urgency ?? 'Standard inspection advised.';

        $causes = is_array($diagnosis->possible_causes) ? $diagnosis->possible_causes : (json_decode($diagnosis->possible_causes, true) ?? []);
        $actions = is_array($diagnosis->recommended_actions) ? $diagnosis->recommended_actions : (json_decode($diagnosis->recommended_actions, true) ?? []);
    @endphp

    <div class="space-y-6 max-w-4xl">
        <!-- Back Link -->
        <div>
            <a href="{{ route('admin.diagnostics.index') }}" class="inline-flex items-center gap-1.5 text-xs font-heading font-semibold text-[#A1A1AA] hover:text-white transition">
                &larr; Back to Diagnostics Queue
            </a>
        </div>

        <!-- Report Header Card -->
        <div class="rounded-xl border border-[#222222] bg-[#111111] p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div class="space-y-1">
                <div class="inline-flex items-center gap-2 rounded bg-[#F63B05]/10 border border-[#F63B05]/20 px-2.5 py-0.5 text-[10px] font-heading font-bold text-[#F63B05] uppercase">
                    <span>AI Diagnostic Report</span>
                </div>
                <h1 class="text-xl font-heading font-bold text-white">Diagnostic Session #{{ $diagnosis->id }}</h1>
                <p class="text-xs text-[#666666]">Generated by VehiCare Multi-Modal AI Engine • {{ $diagnosis->created_at ? $diagnosis->created_at->format('M d, Y h:i A') : 'N/A' }}</p>
            </div>
            <div class="flex items-center gap-2">
                @if($severity === 'CRITICAL')
                    <span class="rounded bg-rose-500/15 border border-rose-500/30 px-3 py-1 text-xs font-heading font-bold text-rose-400">CRITICAL SEVERITY</span>
                @elseif($severity === 'HIGH')
                    <span class="rounded bg-[#F63B05]/15 border border-[#F63B05]/30 px-3 py-1 text-xs font-heading font-bold text-[#F63B05]">HIGH SEVERITY</span>
                @elseif($severity === 'MODERATE')
                    <span class="rounded bg-[#F59E0B]/15 border border-[#F59E0B]/30 px-3 py-1 text-xs font-heading font-bold text-[#F59E0B]">MODERATE SEVERITY</span>
                @else
                    <span class="rounded bg-[#32D583]/15 border border-[#32D583]/30 px-3 py-1 text-xs font-heading font-bold text-[#32D583]">LOW SEVERITY</span>
                @endif
            </div>
        </div>

        <!-- Report Content Sections -->
        <div class="space-y-4">
            
            <!-- SECTION 1: SYMPTOMS -->
            <div class="rounded-xl border border-[#222222] bg-[#111111] p-5 space-y-2">
                <h2 class="text-xs font-heading font-bold text-[#F63B05] uppercase tracking-wider">Symptoms Reported</h2>
                <p class="text-xs text-white leading-relaxed">
                    {{ $diagnosis->symptoms ?: 'General vehicle inquiry.' }}
                </p>
            </div>

            <!-- SECTION 2: AI ANALYSIS SUMMARY -->
            <div class="rounded-xl border border-[#222222] bg-[#111111] p-5 space-y-2">
                <h2 class="text-xs font-heading font-bold text-[#F63B05] uppercase tracking-wider">AI Analysis & Summary</h2>
                <p class="text-xs text-[#A1A1AA] leading-relaxed">
                    {{ $diagnosis->summary ?: 'Analysis completed successfully.' }}
                </p>
            </div>

            <!-- SECTION 3: POSSIBLE CAUSES -->
            <div class="rounded-xl border border-[#222222] bg-[#111111] p-5 space-y-3">
                <h2 class="text-xs font-heading font-bold text-[#F63B05] uppercase tracking-wider">Possible Causes Isolated by AI</h2>
                @if(count($causes) > 0)
                    <ul class="space-y-2 text-xs text-[#A1A1AA] list-disc list-inside">
                        @foreach($causes as $cause)
                            <li>{{ $cause }}</li>
                        @endforeach
                    </ul>
                @else
                    <p class="text-xs text-[#666666]">No mechanical faults isolated.</p>
                @endif
            </div>

            <!-- SECTION 4: RECOMMENDED ACTION & ESTIMATED COST -->
            <div class="grid gap-4 sm:grid-cols-2">
                <div class="rounded-xl border border-[#222222] bg-[#111111] p-5 space-y-2">
                    <h2 class="text-xs font-heading font-bold text-[#F63B05] uppercase tracking-wider">AI Recommended Actions</h2>
                    @if(count($actions) > 0)
                        <ul class="space-y-2 text-xs text-white list-disc list-inside">
                            @foreach($actions as $act)
                                <li>{{ $act }}</li>
                            @endforeach
                        </ul>
                    @else
                        <p class="text-xs text-white leading-relaxed">
                            Routine operational check.
                        </p>
                    @endif
                </div>

                <div class="rounded-xl border border-[#222222] bg-[#111111] p-5 space-y-3">
                    <h2 class="text-xs font-heading font-bold text-[#F63B05] uppercase tracking-wider">Urgency & AI Estimated Repair Cost</h2>
                    <div class="space-y-2 text-xs">
                        <div class="flex justify-between border-b border-[#222222] pb-2">
                            <span class="text-[#666666]">Urgency Advice</span>
                            <span class="font-heading font-bold text-[#F59E0B]">{{ $urgency }}</span>
                        </div>
                        <div class="flex justify-between pt-1">
                            <span class="text-[#666666]">AI Cost Estimate (PHP)</span>
                            <span class="font-heading font-bold text-[#10B981] text-sm">
                                @if($hasCost)
                                    ₱{{ number_format($minCost, 0) }} – ₱{{ number_format($maxCost, 0) }} {{ $currencyCode }}
                                @else
                                    <span class="text-[#666666] font-normal text-xs">N/A (No Repair Needed)</span>
                                @endif
                            </span>
                        </div>
                    </div>
                </div>
            </div>

            <!-- SECTION 5: PROFESSIONAL HELP & SERVICE REFERRAL -->
            <div class="rounded-xl border border-[#222222] bg-[#111111] p-5 space-y-2">
                <h2 class="text-xs font-heading font-bold text-[#F63B05] uppercase tracking-wider">Professional Assistance Referral</h2>
                <div class="flex items-center gap-2">
                    <span class="text-xs text-[#A1A1AA]">Recommendation Status:</span>
                    @if($diagnosis->professional_help_recommended)
                        <span class="font-heading font-bold text-rose-400 text-xs uppercase">RECOMMENDED (Immediate Service Required)</span>
                    @else
                        <span class="font-heading font-bold text-[#10B981] text-xs uppercase">NOT REQUIRED (Self Inspection)</span>
                    @endif
                </div>
                @if($diagnosis->professional_help_reason)
                    <p class="text-xs text-[#666666] mt-1">{{ $diagnosis->professional_help_reason }}</p>
                @endif
            </div>

        </div>

    </div>
</x-admin-layout>
